### ISSUE TITLE
./install.sh stuck on Checking for installed apps in RDP machine

### ISSUE THREAD

**Issue by swissbeats93** [Fmstrat/winapps#23] opened 2020-11-09 15:04 UTC
When i run install it gets stuck on Checking for installed apps in RDP machine and when i run sudo install it tells me to create a winapps.conf file. I already did this and i've updated the paths for office and it still doesn't work

**Comment by ahmadubuntu** [comment] 2020-11-09 15:35
Hi dear developer.

I have the same issue.
I put some echo command in "install.sh" and it goes many times over this line: 

`THIS_RUN=$(stat -t -c %Y ${HOME}/.winapps.installed) `

the content of the "~/.winapps.installed.bat" file:
`
IF EXIST "C:\Program Files\Microsoft Office\Office16\EXCEL.EXE" ECHO excel >> \\tsclient\home\.winapps.installed
IF EXIST "C:\Program Files\Internet Explorer\iexplore.exe" ECHO iexplorer >> \\tsclient\home\.winapps.installed
IF EXIST "C:\Program Files\Microsoft Office\Office16\POWERPNT.EXE" ECHO powerpoint >> \\tsclient\home\.winapps.installed
IF EXIST "C:\Program Files\Microsoft Office\Office16\WINWORD.EXE" ECHO word >> \\tsclient\home\.winapps.installed
`

and I have installed just Powerpoint, Excel, Word from MS Office.

**Comment by Fmstrat** [comment] 2020-11-09 16:04
@ahmadubuntu What do you mean "goes many times"? Is that where it gets stuck?

**Comment by swissbeats93** [comment] 2020-11-09 16:07
> @ahmadubuntu What do you mean "goes many times"? Is that where it gets stuck?

Looks like it, I'm tracing the message to the winapps file in the bin folder but I'm not really sure what the message is telling me is missing

**Comment by Fmstrat** [comment] 2020-11-09 16:23
@swissbeats93 Can you do a `git pull` and then add a `set -x` before line 24 of `/bin/winapps` and a `set +x` after line 35? That's the block and it should point out exactly what's happening.

**Comment by Fmstrat** [comment] 2020-11-09 16:24
Oh wait.. are you missing your config file?

**Comment by swissbeats93** [comment] 2020-11-09 16:25
I do have a config file in $HOME/.config/winapps/winapps.conf

**Comment by swissbeats93** [comment] 2020-11-09 16:31
`if [ ! -f "${HOME}/.config/winapps/winapps.conf" ] && [ ! -f "${HOME}/.winapps" ]; then
	echo "You need to create a ~/.config/winapps/winapps.conf configuration. Exiting..."
	exit
fi`

This is where everything exits right. Question, why are we checking for two files at this point, should both be present or just one of the two.

PS: I added set -x and set +x and i didn't get any new information

**Comment by ahmadubuntu** [comment] 2020-11-09 16:40
> @ahmadubuntu What do you mean "goes many times"? Is that where it gets stuck?

yes

**Comment by ahmadubuntu** [comment] 2020-11-09 16:58
> `if [ ! -f "${HOME}/.config/winapps/winapps.conf" ] && [ ! -f "${HOME}/.winapps" ]; then echo "You need to create a ~/.config/winapps/winapps.conf configuration. Exiting..." exit fi`
> 
> This is where everything exits right. Question, why are we checking for two files at this point, should both be present OR just one of the two and is the second one meant to be a file or a directory.
> 
> PS: I added set -x and set +x and i didn't get any new information because it exits at the 4th line I guess

my winapps.conf doesn't have these contents! It just has the windows username and password as I set it.

**Comment by swissbeats93** [comment] 2020-11-09 17:04
> > `if [ ! -f "${HOME}/.config/winapps/winapps.conf" ] && [ ! -f "${HOME}/.winapps" ]; then echo "You need to create a ~/.config/winapps/winapps.conf configuration. Exiting..." exit fi`
> > This is where everything exits right. Question, why are we checking for two files at this point, should both be present OR just one of the two and is the second one meant to be a file or a directory.
> > PS: I added set -x and set +x and i didn't get any new information because it exits at the 4th line I guess
> 
> my winapps.conf doesn't have these contents! It just has the windows username and password as I set it.

That's what it must have. When I do `[ ! -f "${HOME}/.config/winapps/winapps.conf" ] || echo "DNE"` it prints DNE which is telling me that the file does not exist but the file is there

**Comment by Fmstrat** [comment] 2020-11-09 17:28
> Question, why are we checking for two files at this point, should both be present OR just one of the two and is the second one meant to be a file or a directory.

Because it works with both files. It is a check to see if either exists, and if not, exits.

> That's what it must have. When I do [ ! -f "${HOME}/.config/winapps/winapps.conf" ] || echo "DNE" it prints DNE which is telling me that the file does not exist but the file is there

That's normal behavior. `! -f <file>` is when `not a file`.

What is `echo ${HOME}` on your systems?

**Comment by swissbeats93** [comment] 2020-11-09 17:36
Should it be an and or an or in that case because you need one of them to exist right?

When I call $home it displays correctly but in the case when I was calling home with sudo permissions it was changing to root (which is what made the script fail). In hindsight I’m seeing now that because it was referencing the wrong $HOME the script couldn’t execute even after passing the first loop. I’ll check now because the region bounded set -x and set +x was telling me that I’m not part of the group (correctly because I was root) . I’m trying now as a regular user and we see what happens

**Comment by ahmadubuntu** [comment] 2020-11-09 18:10
> ${HOME}

/home/ahmad

**Comment by ahmadubuntu** [comment] 2020-11-09 18:18
there is nothing important in winapps.log:

`[Mon 09 Nov 2020 08:13:46 PM +0330-20389] START
[Mon 09 Nov 2020 08:13:46 PM +0330-20389] 1:install
[Mon 09 Nov 2020 08:13:46 PM +0330-20389] 2:
[Mon 09 Nov 2020 08:13:46 PM +0330-20389] @:install
[Mon 09 Nov 2020 08:13:46 PM +0330-20389] END
[Mon 09 Nov 2020 08:17:23 PM +0330-4997] START
[Mon 09 Nov 2020 08:17:23 PM +0330-4997] LAST_RAN:1604940226
[Mon 09 Nov 2020 08:17:23 PM +0330-4997] THIS_RUN:1604940443
[Mon 09 Nov 2020 08:17:23 PM +0330-4997] 1:install
[Mon 09 Nov 2020 08:17:23 PM +0330-4997] 2:
[Mon 09 Nov 2020 08:17:23 PM +0330-4997] @:install
[Mon 09 Nov 2020 08:17:23 PM +0330-4997] END
[Mon 09 Nov 2020 09:44:46 PM +0330-21272] START
[Mon 09 Nov 2020 09:44:46 PM +0330-21272] LAST_RAN:1604940443
[Mon 09 Nov 2020 09:44:46 PM +0330-21272] THIS_RUN:1604945686
[Mon 09 Nov 2020 09:44:46 PM +0330-21272] 1:install
[Mon 09 Nov 2020 09:44:46 PM +0330-21272] 2:
[Mon 09 Nov 2020 09:44:46 PM +0330-21272] @:install
[Mon 09 Nov 2020 09:44:46 PM +0330-21272] END
`

**Comment by Fmstrat** [comment] 2020-11-09 19:31
@swissbeats93 Ahh yes, the installer is not mean to be run as root ;)

@ahmadubuntu Sooo.. where is it getting stuck? It seems like it's going through that block just fine.. If you put `set -x` at the top of the `install.sh` and the `winapps` files, it will print out a ton of stuff. If you're willing to attach that here (as a file) I can take a look at it in detail.

**Comment by swissbeats93** [comment] 2020-11-09 19:43
So it eventually worked for me, it was getting stuck inside the while loop for some reason. I added several statements to watch it progress down the script. I'll paste the code here:
`
sudo ls > /dev/null

echo "Installing..."

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "${DIR}/bin/winapps" install

# Check for installed apps
echo -n "  Checking for installed apps in RDP machine..."
rm -f /home/swissbeats93/.winapps.installed.bat
rm -f /home/swissbeats93/.winapps.installed
for F in $(ls "${DIR}/apps"); do
	. "${DIR}/apps/${F}/info"
	echo "IF EXIST \"${WIN_EXECUTABLE}\" ECHO ${F} >> \\\\tsclient\\home\\.winapps.installed" >> /home/swissbeats93/.winapps.installed.bat
done;
touch /home/swissbeats93/.winapps.installed
LAST_RAN=$(stat -t -c %Y /home/swissbeats93/.winapps.installed)
sleep 6
xfreerdp /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +home-drive -wallpaper /span /wm-class:"RDPInstaller" /app:"C:\Windows\System32\cmd.exe" /app-icon:"${DIR}/../icons/windows.svg" /app-cmd:"/C \\\\tsclient\\home\\.winapps.installed.bat" 1> /dev/null 2>&1 &
echo -n '  Successfully connected... '
sleep 6
THIS_RUN=$(stat -t -c %Y /home/swissbeats93/.winapps.installed)
echo "I'm awake"
while (( $THIS_RUN - $LAST_RAN < 5 )); do
	sleep 5
	echo -n "Nap time over"
	THIS_RUN=$(stat -t -c %Y /home/swissbeats93/.winapps.installed)
done
echo "Just woke up"

# Install apps
for F in $(cat "/home/swissbeats93/.winapps.installed" |sed 's/\r/\n/g'); do
	. "${DIR}/apps/${F}/info"
	echo -n "  Configuring ${NAME}..."
	sudo rm -f "/usr/share/applications/${F}.desktop"
	echo "[Desktop Entry]
Name=${NAME}
Exec=${DIR}/bin/winapps ${F} %F
Terminal=false
Type=Application
Icon=${DIR}/apps/${F}/icon.svg
StartupWMClass=${FULL_NAME}
Comment=${FULL_NAME}
Categories=${CATEGORIES}
MimeType=${MIME_TYPES}
" |sudo tee "/usr/share/applications/${F}.desktop" > /dev/null
	sudo rm -f "/usr/local/bin/${F}"
	echo "#!/usr/bin/env bash
${DIR}/bin/winapps ${F} $@
" |sudo tee "/usr/local/bin/${F}" > /dev/null
	sudo chmod a+x "/usr/local/bin/${F}"
	echo " Finished."
done
rm -f "/home/swissbeats93/.winapps.installed"
rm -f "/home/swissbeats93/.winapps.installed.bat"

# Install windows
echo -n "  Configuring Windows..."
sudo rm -f "/usr/share/applications/windows.desktop"
echo "[Desktop Entry]
Name=Windows
Exec=${DIR}/bin/winapps windows %F
Terminal=false
Type=Application
Icon=${DIR}/icons/windows.svg
StartupWMClass=Micorosoft Windows
Comment=Micorosoft Windows
Categories=Windows
" |sudo tee "/usr/share/applications/windows.desktop" > /dev/null
sudo rm -f "/usr/local/bin/windows"
echo "#!/usr/bin/env bash
${DIR}/bin/winapps windows
" |sudo tee "/usr/local/bin/windows" > /dev/null
sudo chmod a+x "/usr/local/bin/windows"
echo " Finished."

echo "Installation complete."
`

**Comment by zacmks** [comment] 2020-11-09 19:49
@Fmstrat, I have the same issue, looks like `.winapps.installed` is not being updated by `.winapps.installed.bat`.

Considering that .winapps.installed.bat, is the one that checks what is installed or not and updates the .winapps.installed file, thus updating the file status. As file status is not being updated, looks like the script gets stuck on the while loop.

In my case, I "think" that the issue is because "xfreerdp ...  \\\\tsclient\\home\\.winapps.installed.bat"..." command is not running well on my side. Maybe because I'm **not** running KVM as a **regular user** (my user), as stated on the tutorial?

I'll be checking the reason for this, I'm just not too much experienced with RDP (that's the reason that I could not interpret quite well just that line...), but can do some shell scripting and libvirt/kvm troubleshooting.


And JFYI guys, I'm not running KVM/libvirt as an regular user because I do use my actual Windows installation (partition), so I can't modify the /dev/{disk,sda,hda,nvme}* as a regular user (without doing some really nasty things of course).

**Comment by swissbeats93** [comment] 2020-11-09 19:52
> @Fmstrat, I have the same issue, looks like `.winapps.installed` is not being updated by `.winapps.installed.bat`.
> 
> Considering that .winapps.installed.bat, is the one that checks what is installed or not and updates the .winapps.installed file, thus updating the file status. As file status is not being updated, looks like the script gets stuck on the while loop.
> 
> In my case, I "think" that the issue is because "xfreerdp ... \\tsclient\home\.winapps.installed.bat"..." command is not running well on my side. Maybe because I'm **not** running KVM as a **regular user** (my user), as stated on the tutorial?
> 
> I'll be checking the reason for this, I'm just not too much experienced with RDP (that's the reason that I could not interpret quite well just that line...), but can do some shell scripting and libvirt/kvm troubleshooting.
> 
> And JFYI guys, I'm not running KVM/libvirt as an regular user because I do use my actual Windows installation (partition), so I can't modify the /dev/{disk,sda,hda,nvme}* as a regular user (without doing some really nasty things of course).

Yeah looks like if the while check doesn't pass the first time then you'll be stuck in an infinite loop

**Comment by SeluMesu** [comment] 2020-11-10 03:12
Im stuck too.

I don't know a lot about bash script, but I think there is a bug in the install.sh file.
If you look it line 19 and 24 they are the same value because the file has not change after it was created. So time of last data modification is the same. If you look at line 28-30
`28 while (( $THIS_RUN - $LAST_RAN < 5 )); do
   29 › sleep 5
   30 › THIS_RUN=$(stat -t -c %Y ${HOME}/.winapps.installed)
 31 done`
it will always be true because THIS_RUN - LAST_RAN is equal 0.

**Comment by Ben8** [comment] 2020-11-10 03:14
I have the same problem. I did a bit of research and read through install.sh and the command `xfreerdp /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +home-drive -wallpaper /span /wm-class:"RDPInstaller" /app:"C:\Windows\System32\cmd.exe" /app-icon:"${DIR}/../icons/windows.svg" /app-cmd:"/C \\\\tsclient\\home\\.winapps.installed.bat"` finishes with an end result of `[21:08:51:663] [22478:22479] [ERROR][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex ERRCONNECT_DNS_NAME_NOT_FOUND [0x00020005]`
Would this help? I can't find any information about the error message

**Comment by Ben8** [comment] 2020-11-10 03:24
> can you explain what the while loop is for?

I'm not an expert at this, but I'm pretty sure the loop is just occasionally checking to see if the file has been modified. The command `xfreerdp /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +home-drive -wallpaper /span /wm-class:"RDPInstaller" /app:"C:\Windows\System32\cmd.exe" /app-icon:"${DIR}/../icons/windows.svg" /app-cmd:"/C \\\\tsclient\\home\\.winapps.installed.bat"` is probably supposed to modify it and the loop is detecting when it has finished. However, on some systems, that command errors out. Since it never completes, the file is never modified and no apps are ever installed.

**Comment by zacmks** [comment] 2020-11-10 06:58
In my case, I was able to find the issue and solution.
It's xfreerdp 2.0.0 related. I updated mine to 2.2.0 and it works now.

In my case the "/app" parameter wasn't working with the xfreerdp command on 2.2.0, you can test yours with/without this param.

Just do a simple test and see:

If this works:
xfreerdp /u:[WIN USER] /p:[WIN PWD] /v:[WIN IP] /app:"C:\Windows\System32\cmd.exe"

Compared to this:
xfreerdp /u:[WIN USER] /p:[WIN PWD] /v:[WIN IP]

Last one shoud work.
Of course the purpose is not the same, first command runs the program itself, last command starts a RDP windowed desktop session.
Thus, as we run the .bat file with cmd.exe using the app param, it'll not work and generate the proper files.

**Comment by connlim** [comment] 2020-11-10 10:10
I also encountered this issue, but for me it turned out that my MS office install location was different from the default. No apps were being found so `.winapps.installed` wasn't being updated and it got stuck in an infinite loop.

Basically, as long as anything in the `xfreerdp` command fails (authentication error, no apps found, etc), the script will get stuck on `Checking for installed apps...` infinitely. 

For anybody having this issue , try running the command directly to see if xfreerdp throws up any issue: 

```bash
# Populate necessary variables
RDP_USER=<your windows user>
RDP_PASS=<your windows pass>
DIR=<your winapps directory>

# Get IP
virsh start RDPWindows
RDP_IP=$(virsh net-dhcp-leases default |grep RDPWindows |awk '{print $5}')
RDP_IP=${RDP_IP%%\/*}

# Run problematic command
xfreerdp /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +home-drive -wallpaper /span /wm-class:"RDPInstaller" /app:"C:\Windows\System32\cmd.exe" /app-icon:"${DIR}/../icons/windows.svg" /app-cmd:"/C \\\\tsclient\\home\\.winapps.installed.bat"
```

**Comment by aendi123** [comment] 2020-11-10 11:09
I use my own custom Windows 10 Education VM on Fedora. I had to do two things to get it working:

1. The paths of my Office programs on Windows were different. I changed them in apps/_program_/info
2. This command (don't forget to set or replace the vars)
`xfreerdp /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +home-drive -wallpaper /span /wm-class:"RDPInstaller" /app:"C:\Windows\System32\cmd.exe" /app-icon:"${DIR}/../icons/windows.svg" /app-cmd:"/C \\\\tsclient\\home\\.winapps.installed.bat"`
throwed the error
`[11:53:06:717] [27924:27942] [ERROR][com.freerdp.client.x11] - RAIL exec error: execResult=RAIL_EXEC_E_NOT_IN_ALLOWLIST NtError=0x15`

To get rid of it you have to to create the DWORD `fAllowUnlistedRemotePrograms` with value `1` under `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services`

**Comment by Fmstrat** [comment] 2020-11-10 18:51
@aendi123 Hmm.. did you `Merge kvm/RDPApps.reg into the registry to enable RDP Applications` as per the readme? That's a different key you have there, and I haven't experienced the need for it specifically.

**Comment by Fmstrat** [comment] 2020-11-10 18:52
@connlim I think you found the issue. It's when none are found. Thanks!

**Comment by Fmstrat** [comment] 2020-11-10 18:54
@SeluMesu You're missing the step in the middle where FreeRDP runs and updates that file

**Comment by Fmstrat** [comment] 2020-11-10 20:37
Fixed in https://github.com/Fmstrat/winapps/commit/bd3c321d1a48b710ad991ce25e06644f5703c2c0

Please reopen if problem persists.

**Closed by Fmstrat** 2020-11-10 20:37 UTC

**Comment by industrialist** [comment] 2020-11-11 01:10
Yep, ran that command in the terminal first in isolation and now works fine.

**Comment by ahmadubuntu** [comment] 2020-11-11 14:44
Probably I found the solution for myself:


I tested the command which @zacmks pointed:
`xfreerdp /u:[WIN USER] /p:[WIN PWD] /v:[WIN IP] /app:"C:\Windows\System32\cmd.exe"
`
then it showed this:
```
The above X.509 certificate could not be verified, possibly because you do not have
the CA certificate in your certificate store, or the certificate has expired.
Please look at the OpenSSL documentation on how to add a private CA to the store.
Do you trust the above certificate? (Y/T/N) 
```
I answered: y
and it ran CMD.
after killing that process, I ran the ./install.sh again and it works now.

**Comment by Fmstrat** [comment] 2020-11-12 15:54
Dup: https://github.com/Fmstrat/winapps/issues/41

**Comment by ericcurtin** [comment] 2020-11-17 16:24
That @aendi123 the `fAllowUnlistedRemotePrograms` registry setting is really important, fixed my problem.

**Comment by Fmstrat** [comment] 2020-11-18 20:21
https://github.com/Fmstrat/winapps/commit/ed827a6b248b06d281e5aa2a19afff8ec857137f
